defmodule MssqlexV3.ErrorCode do
  def code_to_name('01000'), do: :general_warning
  def code_to_name('01001'), do: :cursor_operation_conflict
  def code_to_name('01002'), do: :disconnect_error
  def code_to_name('01003'), do: :null_value_eliminated_in_set_function
  def code_to_name('01004'), do: :string_data_right_truncated
  def code_to_name('01006'), do: :privilege_not_revoked
  def code_to_name('01007'), do: :privilege_not_granted
  def code_to_name('01S00'), do: :invalid_connection_string_attribute
  def code_to_name('01S01'), do: :error_in_row
  def code_to_name('01S02'), do: :option_value_changed
  def code_to_name('01S06'), do: :attempt_to_fetch_before_the_result_set_returned_the_first_rowset
  def code_to_name('01S07'), do: :fractional_truncation
  def code_to_name('01S08'), do: :error_saving_file_dsn
  def code_to_name('01S09'), do: :invalid_keyword
  def code_to_name('07001'), do: :wrong_number_of_parameters
  def code_to_name('07002'), do: :count_field_incorrect
  def code_to_name('07005'), do: :prepared_statement_not_a_cursor_specification
  def code_to_name('07006'), do: :restricted_data_type_attribute_violation
  def code_to_name('07009'), do: :invalid_descriptor_index
  def code_to_name('07S01'), do: :invalid_use_of_default_parameter
  def code_to_name('08001'), do: :connection_exception # :client_unable_to_establish_connection
  def code_to_name('08002'), do: :connection_exception # :connection_name_in_use
  def code_to_name('08003'), do: :connection_exception # :connection_not_open
  def code_to_name('08004'), do: :connection_exception # :server_rejected_the_connection
  def code_to_name('08007'), do: :connection_exception # :connection_failure_during_transaction
  def code_to_name('08S01'), do: :connection_exception # :communication_link_failure
  def code_to_name('21S01'), do: :insert_value_list_does_not_match_column_list
  def code_to_name('21S02'), do: :degree_of_derived_table_does_not_match_column_list
  def code_to_name('22001'), do: :string_data_right_truncated
  def code_to_name('22002'), do: :indicator_variable_required_but_not_supplied
  def code_to_name('22003'), do: :numeric_value_out_of_range
  def code_to_name('22007'), do: :invalid_datetime_format
  def code_to_name('22008'), do: :datetime_field_overflow
  def code_to_name('22012'), do: :division_by_zero
  def code_to_name('22015'), do: :interval_field_overflow
  def code_to_name('22018'), do: :invalid_character_value_for_cast_specification
  def code_to_name('22019'), do: :invalid_escape_character
  def code_to_name('22025'), do: :invalid_escape_sequence
  def code_to_name('22026'), do: :string_data_length_mismatch
  def code_to_name('23000'), do: :integrity_constraint_violation
  def code_to_name('24000'), do: :invalid_cursor_state
  def code_to_name('25000'), do: :invalid_transaction_state
  def code_to_name('25S01'), do: :transaction_state
  def code_to_name('25S02'), do: :transaction_is_still_active
  def code_to_name('25S03'), do: :transaction_is_rolled_back
  def code_to_name('28000'), do: :invalid_authorization_specification
  def code_to_name('34000'), do: :invalid_cursor_name
  def code_to_name('3C000'), do: :duplicate_cursor_name
  def code_to_name('3D000'), do: :invalid_catalog_name
  def code_to_name('3F000'), do: :invalid_schema_name
  def code_to_name('40001'), do: :serialization_failure
  def code_to_name('40002'), do: :integrity_constraint_violation
  def code_to_name('40003'), do: :statement_completion_unknown
  def code_to_name('42000'), do: :syntax_error_or_access_violation
  def code_to_name('42S01'), do: :base_table_or_view_already_exists
  def code_to_name('42S02'), do: :base_table_or_view_not_found
  def code_to_name('42S11'), do: :index_already_exists
  def code_to_name('42S12'), do: :index_not_found
  def code_to_name('42S21'), do: :column_already_exists
  def code_to_name('42S22'), do: :column_not_found
  def code_to_name('44000'), do: :with_check_option_violation
  def code_to_name('HY000'), do: :general_error
  def code_to_name('HY001'), do: :memory_allocation_error
  def code_to_name('HY003'), do: :invalid_application_buffer_type
  def code_to_name('HY004'), do: :invalid_sql_data_type
  def code_to_name('HY007'), do: :associated_statement_is_not_prepared
  def code_to_name('HY008'), do: :operation_canceled
  def code_to_name('HY009'), do: :invalid_use_of_null_pointer
  def code_to_name('HY010'), do: :function_sequence_error
  def code_to_name('HY011'), do: :attribute_cannot_be_set_now
  def code_to_name('HY012'), do: :invalid_transaction_operation_code
  def code_to_name('HY013'), do: :memory_management_error
  def code_to_name('HY014'), do: :limit_on_the_number_of_handles_exceeded
  def code_to_name('HY015'), do: :no_cursor_name_available
  def code_to_name('HY016'), do: :cannot_modify_an_implementation_row_descriptor
  def code_to_name('HY017'), do: :invalid_use_of_an_automatically_allocated_descriptor_handle
  def code_to_name('HY018'), do: :server_declined_cancel_request
  def code_to_name('HY019'), do: :non_character_and_non_binary_data_sent_in_pieces
  def code_to_name('HY020'), do: :attempt_to_concatenate_a_null_value
  def code_to_name('HY021'), do: :inconsistent_descriptor_information
  def code_to_name('HY024'), do: :invalid_attribute_value
  def code_to_name('HY090'), do: :invalid_string_or_buffer_length
  def code_to_name('HY091'), do: :invalid_descriptor_field_identifier
  def code_to_name('HY092'), do: :invalid_attribute_or_option_identifier
  def code_to_name('HY095'), do: :function_type_out_of_range
  def code_to_name('HY096'), do: :invalid_information_type
  def code_to_name('HY097'), do: :column_type_out_of_range
  def code_to_name('HY098'), do: :scope_type_out_of_range
  def code_to_name('HY099'), do: :nullable_type_out_of_range
  def code_to_name('HY100'), do: :uniqueness_option_type_out_of_range
  def code_to_name('HY101'), do: :accuracy_option_type_out_of_range
  def code_to_name('HY103'), do: :invalid_retrieval_code
  def code_to_name('HY104'), do: :invalid_precision_or_scale_value
  def code_to_name('HY105'), do: :invalid_parameter_type
  def code_to_name('HY106'), do: :fetch_type_out_of_range
  def code_to_name('HY107'), do: :row_value_out_of_range
  def code_to_name('HY109'), do: :invalid_cursor_position
  def code_to_name('HY110'), do: :invalid_driver_completion
  def code_to_name('HY111'), do: :invalid_bookmark_value
  def code_to_name('HYC00'), do: :optional_feature_not_implemented
  def code_to_name('HYT00'), do: :timeout_expired
  def code_to_name('HYT01'), do: :connection_timeout_expired
  def code_to_name('IM001'), do: :driver_does_not_support_this_function
  def code_to_name('IM002'), do: :data_source_name_not_found_and_no_default_driver_specified
  def code_to_name('IM003'), do: :specified_driver_could_not_be_loaded
  def code_to_name('IM004'), do: :driver_sql_alloc_handle_on_sql_handle_env_failed
  def code_to_name('IM005'), do: :driver_sql_alloc_handle_on_sql_handle_dbc_failed
  def code_to_name('IM006'), do: :driver_sql_setconnect_attr_failed
  def code_to_name('IM007'), do: :no_data_source_or_driver_specified_dialog_prohibited
  def code_to_name('IM008'), do: :dialog_failed
  def code_to_name('IM009'), do: :unable_to_load_translation_dll
  def code_to_name('IM010'), do: :data_source_name_too_long
  def code_to_name('IM011'), do: :driver_name_too_long
  def code_to_name('IM012'), do: :driver_keyword_syntax_error
  def code_to_name('IM013'), do: :trace_file_error
  def code_to_name('IM014'), do: :invalid_name_of_file_dsn
  def code_to_name('IM015'), do: :corrupt_file_data_source
  def code_to_name(:not_allowed_in_transaction), do: :not_allowed_in_transaction
  def code_to_name(_), do: :feature_not_supported
end
